---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
spec:
  selector:
    matchLabels:
      app: test-1
  replicas: 1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      containers:
      - name: test-1
        image: test-1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
